export const actionTypes = {
    SET_USER: 'SET_USER',
    SET_LOADING: 'SET_LOADING',
    SET_MESSAGE_TOAST: 'SET_MESSAGE_TOAST',
    SET_CLEAR_MESSAGE_TOAST_BY_ID: 'SET_CLEAR_MESSAGE_TOAST_BY_ID',
    SET_LEARNING_RESOURCES: 'SET_LEARNING_RESOURCES',
    SET_FUTURE_PROJECTS: 'SET_FUTURE_PROJECTS',
    SET_NPM_PACKAGES: 'SET_NPM_PACKAGES',
    SET_BOOKS: 'SET_BOOKS',
    SET_DARK_THEME: 'SET_DARK_THEME',
    SET_LIGHT_THEME: 'SET_LIGHT_THEME',
    SET_LOGOUT_USER: 'SET_LOGOUT_USER'
}
