export const appState = {
    isLoading: false,
    theme: {
        dark: false,
        light: true,
    },
    backdrop: {
        open: false,
        child: null,
    },
    user: null,
    messageToast: [],
    javascript: [],
    css: [],
    reactjs: [],
    testing: [],
    databases: [],
    nodejs: [],
    npmPackages: [],
    projects: [],
    books: [],
    futureProjects: [],
    others: [],
    reRender: false,
};
